id: P000404
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD430
  title: བོད་ཀྱི་བཀྲ་ཤིས་པའི་རྒྱུན་རིས་གསར་འགྲེལ།
  author: ''
  volumes:
    4be1921b143841bb99b7646dafdd1d55:
      image_group_id: I2PD17816
      title: Volume 1 of bod kyi bkra shis pa'i rgyun ris gsar 'grel/
      volume_number: 1
      total_pages: 176
      base_file: v001.txt
ebook_metadata:
  title: བོད་ཀྱི་བཀྲ་ཤིས་པའི་རྒྱུན་རིས་གསར་འགྲེལ།
  author: ''
  sku: P000404
  cover: cover.jpg
  layers:
  - pagination
