id: P000404
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:38:13.153854
source_metadata:
  id: bdr:W3PD430
  title: བོད་ཀྱི་བཀྲ་ཤིས་པའི་རྒྱུན་རིས་གསར་འགྲེལ།
  author: ''
  volumes:
    4be1921b143841bb99b7646dafdd1d55:
      image_group_id: I2PD17816
      title: Volume 1 of bod kyi bkra shis pa'i rgyun ris gsar 'grel/
      volume_number: 1
      total_pages: 176
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
